apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: limitcheck
  namespace: kube-system
webhooks:
  - name: limitcheck.loodse.com
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    failurePolicy: Fail
    clientConfig:
      service: 
        name: limitcheck
        namespace: kube-system
        path: "/validate"
      caBundle: "${CA_BUNDLE}"

